service: adopt-service

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
  apiGateway:
    shouldStartNameWithService: true
  # Enable CORS for all API Gateway responses
  cors: true

functions:
  # Fetch all pets
  getPets:
    handler: handler.getPets
    events:
      - http:
          path: pets
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  # Create a new pet
  createPet:
    handler: handler.createPet
    events:
      - http:
          path: pets
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  # Fetch all users
  getUsers:
    handler: handler.getUsers
    events:
      - http:
          path: users
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

  # Create a new user
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: false

plugins:
  - serverless-dotenv-plugin
