service: adopt-service

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}  # ✅ Needed to decode the token!
  apiGateway:
    shouldStartNameWithService: true

functions:
  getPets:
    handler: handler.getPets
    events:
      - http:
          path: pets
          method: get
          cors:
            origin: "http://adopt-a-pet-frontend-2025.s3-website-us-east-1.amazonaws.com"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  createPet:
    handler: handler.createPet
    events:
      - http:
          path: pets
          method: post
          cors:
            origin: "http://adopt-a-pet-frontend-2025.s3-website-us-east-1.amazonaws.com"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  getUsers:
    handler: handler.getUsers
    events:
      - http:
          path: users
          method: get
          cors:
            origin: "http://adopt-a-pet-frontend-2025.s3-website-us-east-1.amazonaws.com"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
          cors:
            origin: "http://adopt-a-pet-frontend-2025.s3-website-us-east-1.amazonaws.com"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  graphql:
    handler: graphqlHandler.graphqlHandler
    events:
      - http:
          path: graphql
          method: any
          cors:
            origin: "http://adopt-a-pet-frontend-2025.s3-website-us-east-1.amazonaws.com"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

plugins:
  - serverless-dotenv-plugin

package:
  include:
    - utils/**
